name: SmartFlowAI CI/CD Pipeline 🚀

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # === Checkout Repo ===
      - name: Checkout repository
        uses: actions/checkout@v3

      # === Node Setup ===
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      # === Install Dependencies ===
      - name: Install dependencies
        run: npm install

      # === Run Checks / Lint / TypeScript ===
      - name: Run Master Check
        run: |
          chmod +x scripts/master-check.sh
          ./scripts/master-check.sh
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}

      # === Build Project ===
      - name: Build Project
        run: npm run build

      # === Deploy to Render (only if checks + build pass) ===
      - name: Deploy to Render
        if: success()
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
