name: SmartFlowAI Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install --include=dev

      # 4. Run master-sync.sh (handles Render + DB + build)
      - name: Super Sync & Deploy
        run: ./scripts/master-sync.sh
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      # 5. Sync secrets to Replit
      - name: Sync secrets to Replit
        run: |
          curl -X POST "https://replit.com/api/v0/repls/${{ secrets.REPLIT_REPL_ID }}/secrets" \
            -H "Authorization: Bearer ${{ secrets.REPLIT_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '[
              {"key":"JWT_SECRET","value":"${{ secrets.JWT_SECRET }}"},
              {"key":"OPENAI_API_KEY","value":"${{ secrets.OPENAI_API_KEY }}"},
              {"key":"DATABASE_URL","value":"${{ secrets.DATABASE_URL }}"},
              {"key":"STRIPE_SECRET_KEY","value":"${{ secrets.STRIPE_SECRET_KEY }}"},
              {"key":"SMTP_PASSWORD","value":"${{ secrets.SMTP_PASSWORD }}"}
            ]'

      # 6. Push back changes (like updated .env.example)
      - name: Push back changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .env.example dist || true
          git commit -m "chore: auto-sync secrets & build [CI skip]" || true
          git push
